#!/usr/bin/env python

import argparse
import logging
from PySide6 import QtWidgets

from metsearch.mainwindow import MainWindow


def configure_logging(args):
    logging.basicConfig(
        level=logging.WARNING,
        format="%(levelname)s [%(name)s] %(message)s"
    )
    logging.getLogger("urllib3.connectionpool").setLevel(logging.ERROR)

    if args["info"]:
        logging.getLogger().setLevel(logging.INFO)
    if args["debug"]:
        logging.getLogger().setLevel(logging.DEBUG)


def main():
    args = parse_args()
    configure_logging(args)

    app = QtWidgets.QApplication([])
    window = MainWindow()
    window.ui.show()
    app.exec()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--info", action="store_true")
    parser.add_argument("--debug", action="store_true")
    return vars(parser.parse_args())


if __name__ == "__main__":
    main()
